version: "3.9"
services:
  sungrow-go:
    build:
      context: ./../
      dockerfile: ./docker/Dockerfile
    image: stefanroeck/sungrow
    container_name: sungrow
    restart: unless-stopped
    environment:
      - SUNGROW_PROTOCOL=${SUNGROW_PROTOCOL:-wss}
      - SUNGROW_HOST=${SUNGROW_HOST}
      - SUNGROW_PORT=${SUNGROW_PORT:-8082}
      - SUNGROW_USER=${SUNGROW_USER}
      - SUNGROW_PASSWORD=${SUNGROW_PASSWORD}
      - MQTT_URL=${MQTT_URL}
      - MQTT_TOPIC=${MQTT_TOPIC:-sungrow/stats}
      - MQTT_CLIENTID=${MQTT_CLIENTID}
      - MQTT_USER=${MQTT_USER}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - SLEEP=30
