version: "3.9"
services:
  sungrow-go:
    build:
      context: ./../
      dockerfile: ./docker/Dockerfile
    image: stefanroeck/sungrow
    container_name: sungrow
    restart: unless-stopped
    env_file:
      - .env
